version: '3'
<<<<<<< HEAD
  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "10.200.1.35:3000:3000"
      network_mode: bridge
      depends_on:
        - solr
    solr:
      image: solr
      ports:
        - "10.200.1.35:8983:8983"
      network_mode: bridge
      volumes:
        - data:/var/solr
  volumes:
    data:
=======
services:
  web:
    environment:
      - SWIFT_USERNAME=xxx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - solr
    volumes:
      - /root/demo-blacklight:/app
    networks:
      - test
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    networks:
      - test
volumes:
  data:
networks:
  test:
>>>>>>> usability-testing-mirador
