version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./public:/app/public
      - ./vendor:/app/vendor
volumes:
  data:
networks:
  test: