version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    network_mode: bridge
    depends_on:
      - solr
  solr:
    image: solr
    ports:
     - "8993:8993"
    network_mode: bridge
    volumes:
      - data:/var/solr
volumes:
  data: