version: '3'
services:
  web:
    environment:
      - SWIFT_USERNAME=xxx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - solr
    volumes:
      - /root/demo-blacklight:/app
    networks:
      - test
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    networks:
      - test
volumes:
  data:
networks:
  test:
