version: '3'
  services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "10.200.1.35:3000:3000"
      network_mode: bridge
      depends_on:
        - solr
    solr:
      image: solr
      ports:
        - "10.200.1.35:8983:8983"
      network_mode: bridge
      volumes:
        - data:/var/solr
  volumes:
    data:
