load_defaults: 8.0.1
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solrm:8984/solr/blacklight" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solrm:8984/solr/blacklight" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solrm:8984/solr/blacklight" %>
