load_defaults: 8.0.1
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://24.199.108.51:8983/solr/blacklight" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://24.199.108.51:8983/solr/blacklight" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://24.199.108.51:8983/solr/blacklight" %>
