load_defaults: 8.0.1
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://159.203.33.98:8983/solr/blacklight" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://159.203.33.98:8983/solr/blacklight" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://159.203.33.98:8983/solr/blacklight" %>
