production:
  solr:
    hostname: blacklight.crkn-demo-test.ca
    port: 8983
    log_level: WARNING
    path: /solr/blacklight
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: blacklight.crkn-demo-test.ca
    port: 8983
    log_level: WARNING
    path: /solr/coseblacklightarch2

test:
  solr:
    hostname: blacklight.crkn-demo-test.ca
    port: 8983
    log_level: WARNING
    path: /solr/blacklight
    