production:
  solr:
    hostname: parl-blacklight-test-bcwg7.ondigitalocean.app
    port: 8983
    log_level: WARNING
    path: /solr/lop-blacklight
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: parl-blacklight-test-bcwg7.ondigitalocean.app
    port: 8983
    log_level: WARNING
    path: /solr/coseblacklightarch2

test:
  solr:
    hostname: parl-blacklight-test-bcwg7.ondigitalocean.app
    port: 8983
    log_level: WARNING
    path: /solr/lop-blacklight
    