production:
  solr:
    hostname: sea-lion-app-kv5jd.ondigitalocean.app
    port: 8983
    log_level: WARNING
    path: /solr/blacklight
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: sea-lion-app-kv5jd.ondigitalocean.app
    port: 8983
    log_level: WARNING
    path: /solr/coseblacklightarch2

test:
  solr:
    hostname: sea-lion-app-kv5jd.ondigitalocean.app
    port: 8983
    log_level: WARNING
    path: /solr/blacklight
    