name: Docker Image CI

on:
  push:
    branches: [ "usability-testing" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: docker-compose build
    - name: Tag
      run: docker tag docker.io/library/demo-blacklight_web ghcr.io/crkn-rcdr/demo-blacklight_web:latest
    - name: Push
      run: docker push ghcr.io/crkn-rcdr/demo-blacklight_web:latest
